using System.Text;
using System.Threading.RateLimiting;
using AiReceptionist.Api.Common;
using AiReceptionist.Api.Data;
using AiReceptionist.Api.Data.Repositories;
using AiReceptionist.Api.Middleware;
using AiReceptionist.Api.Services;
using Lib.Net.Http.WebPush;
using Lib.Net.Http.WebPush.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.IdentityModel.Tokens;

// One-off setup: `dotnet run --project backend/AiReceptionist.Api -- vapid` prints a fresh key
// pair for browser notifications and exits. Kept as a command rather than generated on the fly,
// because the pair has to outlive restarts: a browser only accepts pushes signed by the key it
// subscribed against, so regenerating silently would unsubscribe every device at once.
if (args.Length > 0 && args[0].Equals("vapid", StringComparison.OrdinalIgnoreCase))
{
    var (vapidPublic, vapidPrivate) = VapidKeys.Generate();
    Console.WriteLine("Add these to appsettings.Local.json (which is git-ignored):");
    Console.WriteLine();
    Console.WriteLine("  \"Push\": {");
    Console.WriteLine($"    \"PublicKey\": \"{vapidPublic}\",");
    Console.WriteLine($"    \"PrivateKey\": \"{vapidPrivate}\",");
    Console.WriteLine("    \"Subject\": \"mailto:you@yourbusiness.com\"");
    Console.WriteLine("  }");
    Console.WriteLine();
    Console.WriteLine("The public key is handed to every browser that subscribes. Keep the private");
    Console.WriteLine("key secret, and do not replace the pair once devices are registered.");
    return;
}

var builder = WebApplication.CreateBuilder(args);

// Git-ignored local secrets (e.g. Retell API key) — see appsettings.Local.json
builder.Configuration.AddJsonFile("appsettings.Local.json", optional: true, reloadOnChange: true);

// ---------- Services ----------
builder.Services.AddControllers();

// Swagger is served in Development only (see the pipeline below), so only build the generator
// there — production then has nothing registered that a stray UseSwagger() could expose.
if (builder.Environment.IsDevelopment())
{
    builder.Services.AddEndpointsApiExplorer();
    builder.Services.AddSwaggerGen();
}

builder.Services.AddHttpContextAccessor();
builder.Services.AddResponseCompression();

// Payload encryption for the web app (see PayloadEncryptionMiddleware). Singleton: it owns the
// RSA key pair the browser wraps its per-session AES key with, plus the live sessions.
builder.Services.AddSingleton<IPayloadKeyRing, PayloadKeyRing>();

builder.Services.AddSingleton<IDbConnectionFactory, DbConnectionFactory>();
builder.Services.AddScoped<ITenantProvider, TenantProvider>();
builder.Services.AddScoped<ITokenService, TokenService>();
builder.Services.AddScoped<IPromptBuilderService, PromptBuilderService>();

// Retell AI integration (SRS §14–15): agent sync + background re-sync worker
builder.Services.AddHttpClient<IRetellService, RetellService>();
builder.Services.AddSingleton<IRetellSyncQueue, RetellSyncQueue>();
builder.Services.AddHostedService<RetellSyncWorker>();

// Transferred-call intent capture: mine transcripts for booking intent (Anthropic)
builder.Services.AddHttpClient<ICallIntentService, CallIntentService>();
builder.Services.AddHostedService<CallIntentWorker>();

builder.Services.AddScoped<IAuthRepository, AuthRepository>();
builder.Services.AddScoped<ICustomerRepository, CustomerRepository>();
builder.Services.AddScoped<IAppointmentRepository, AppointmentRepository>();
builder.Services.AddScoped<IEmployeeRepository, EmployeeRepository>();
builder.Services.AddScoped<INotificationRepository, NotificationRepository>();
builder.Services.AddScoped<ICatalogRepository, CatalogRepository>();
builder.Services.AddScoped<ICallRepository, CallRepository>();
builder.Services.AddScoped<IKnowledgeRepository, KnowledgeRepository>();
builder.Services.AddScoped<IHolidayRepository, HolidayRepository>();
builder.Services.AddScoped<ISettingsRepository, SettingsRepository>();
builder.Services.AddScoped<IDashboardRepository, DashboardRepository>();
builder.Services.AddScoped<IAuditRepository, AuditRepository>();
builder.Services.AddScoped<IAiToolsRepository, AiToolsRepository>();
builder.Services.AddScoped<ICallActionSuggestionRepository, CallActionSuggestionRepository>();
builder.Services.AddScoped<IRetellConnectionRepository, RetellConnectionRepository>();
builder.Services.AddScoped<IPromptTemplateRepository, PromptTemplateRepository>();

// Billing: tiers, Stripe, usage periods and the overage carried to the next invoice.
// ---------- Browser notifications (Web Push) ----------
// The owner is not sitting in the dashboard, so a booking taken overnight — or an emergency taken
// at any hour — is invisible until they next sign in. Web Push reaches the phone with the app
// closed and costs nothing to send: the VAPID pair below is generated by this deployment for
// itself, and delivery rides on the browser vendors' own push services.
var pushOptions = builder.Configuration.GetSection("Push").Get<PushOptions>() ?? new PushOptions();
builder.Services.AddSingleton(pushOptions);
builder.Services.AddScoped<INotificationService, NotificationService>();
builder.Services.AddHostedService<AlertEscalationWorker>();

// A typed client so the handler is pooled and rotated like every other outbound call. The VAPID
// credential is attached here rather than per-send: it identifies the deployment, not the message.
builder.Services.AddHttpClient(nameof(PushServiceClient))
    .AddTypedClient((http, sp) =>
    {
        var options = sp.GetRequiredService<PushOptions>();
        var client = new PushServiceClient(http);
        if (options.Configured)
            client.DefaultAuthentication = new VapidAuthentication(options.PublicKey!, options.PrivateKey!)
            {
                Subject = options.Subject,
            };
        return client;
    });

builder.Services.AddScoped<IBillingRepository, BillingRepository>();
builder.Services.AddSingleton<IStripeGateway, StripeGateway>();
builder.Services.AddScoped<IBillingService, BillingService>();
builder.Services.AddHostedService<BillingPeriodWorker>();
// The webhook is the fast path for payments; this is the guarantee. It re-reads what Stripe has
// actually collected and applies anything no delivery ever arrived for.
builder.Services.AddHostedService<BillingReconciliationWorker>();

// Whether an organization may be answered at all. Read by the inbound-call webhook and by every
// live-call tool, so a customer on no plan — or one who has stopped paying — is not served.
builder.Services.AddScoped<ICallEntitlementService, CallEntitlementService>();
// Refusing the webhook only works while Retell can reach us. Detaching the number is the stop that
// holds regardless, and this is what applies and lifts it without an operator in the loop.
builder.Services.AddHostedService<CallEntitlementWorker>();

// JWT authentication (SRS §5, §20)
var jwtSecret = Environment.GetEnvironmentVariable("JWT__SECRET") ?? builder.Configuration["Jwt:Secret"];

// The signing key is the single thing standing between an attacker and a forged token for any
// tenant or role (orgId + role are claims). A shipped placeholder is public knowledge, so refuse
// to start on one rather than run a silently-forgeable system.
if (string.IsNullOrWhiteSpace(jwtSecret) || jwtSecret.Length < 32 ||
    jwtSecret.Contains("CHANGE_ME", StringComparison.OrdinalIgnoreCase))
{
    throw new InvalidOperationException(
        "Jwt:Secret is missing, too short, or still the placeholder. Set a random secret of at " +
        "least 32 characters via the JWT__SECRET environment variable (or Jwt:Secret in " +
        "appsettings.Local.json) before starting the API.");
}
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = builder.Configuration["Jwt:Issuer"],
            ValidAudience = builder.Configuration["Jwt:Audience"],
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSecret)),
            ClockSkew = TimeSpan.FromSeconds(30)
        };
    });
builder.Services.AddAuthorization();

// CORS restricted to the frontend origin (SRS §20)
var allowedOrigins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>() ?? [];
// AllowCredentials is required for the httpOnly refresh cookie to be sent on cross-origin
// calls. It is only legal alongside an explicit origin list (never AllowAnyOrigin).
builder.Services.AddCors(options =>
    options.AddPolicy("Frontend", policy =>
        policy.WithOrigins(allowedOrigins).AllowAnyHeader().AllowAnyMethod().AllowCredentials()));

// Rate limiting (SRS §20 — Redis-backed in production; in-memory fixed window here)
builder.Services.AddRateLimiter(options =>
{
    options.RejectionStatusCode = StatusCodes.Status429TooManyRequests;
    options.GlobalLimiter = PartitionedRateLimiter.Create<HttpContext, string>(ctx =>
    {
        // Retell's live-call tools and webhooks arrive from few egress IPs at high volume —
        // give them their own generous bucket so calls are never throttled mid-conversation.
        var path = ctx.Request.Path.Value ?? "";
        if (path.StartsWith("/api/v1/ai/tools", StringComparison.OrdinalIgnoreCase) ||
            path.StartsWith("/api/v1/webhooks", StringComparison.OrdinalIgnoreCase))
            return RateLimitPartition.GetFixedWindowLimiter("retell-traffic",
                _ => new FixedWindowRateLimiterOptions { PermitLimit = 3000, Window = TimeSpan.FromMinutes(1) });

        return RateLimitPartition.GetFixedWindowLimiter(
            ctx.Connection.RemoteIpAddress?.ToString() ?? "anonymous",
            _ => new FixedWindowRateLimiterOptions { PermitLimit = 200, Window = TimeSpan.FromMinutes(1) });
    });
    // Credential endpoints (login / register / refresh) get a tight bucket to stop online
    // password guessing. It MUST be partitioned per client IP: a single shared limiter would
    // let one attacker burn the whole allowance and lock every tenant out of signing in.
    options.AddPolicy("login", ctx => RateLimitPartition.GetFixedWindowLimiter(
        $"login:{ctx.Connection.RemoteIpAddress?.ToString() ?? "anonymous"}",
        _ => new FixedWindowRateLimiterOptions { PermitLimit = 10, Window = TimeSpan.FromMinutes(1) }));

    // Token refresh is a legitimate per-page-load operation (the access token is held in
    // memory only), so it needs far more headroom than password entry — but still capped.
    options.AddPolicy("refresh", ctx => RateLimitPartition.GetFixedWindowLimiter(
        $"refresh:{ctx.Connection.RemoteIpAddress?.ToString() ?? "anonymous"}",
        _ => new FixedWindowRateLimiterOptions { PermitLimit = 60, Window = TimeSpan.FromMinutes(1) }));
});

builder.Services.AddHealthChecks();

var app = builder.Build();

// ---------- Database bootstrap (creates AiDB + schema + demo seed) ----------
try
{
    DbInitializer.Initialize(app.Configuration, app.Logger);
}
catch (Exception ex)
{
    app.Logger.LogError(ex,
        "Could not initialize AiDB. Ensure SQL Server is running and the connection string is correct. " +
        "The API will start, but database calls will fail until the database is available.");
}

// ---------- Secret hygiene ----------
// The Retell key is not merely an API credential: it doubles as the HMAC secret for inbound
// webhooks and live-call tool tokens, so leaking it lets an attacker forge traffic into this API
// rather than just spend Retell credits. Because GetEffectiveAsync accepts Retell:ApiKey from any
// configuration source, a key pasted into a tracked file works silently while shipping with the
// repo — the failure mode is invisible at runtime, so report it at boot instead.
foreach (var (key, label) in new[]
{
    ("Retell:ApiKey", "Retell API key"),
    ("Jwt:Secret", "JWT signing key"),
    ("Platform:AdminKey", "platform administration key"),
    ("Anthropic:ApiKey", "Anthropic API key"),
    ("Smtp:Password", "SMTP password"),
    ("Push:PrivateKey", "web push (VAPID) private key"),
    ("Stripe:SecretKey", "Stripe secret key"),
    ("Stripe:WebhookSecret", "Stripe webhook signing secret"),
})
{
    foreach (var file in TrackedConfigFilesFor(app.Configuration, key))
        app.Logger.LogWarning(
            "SECURITY: {Label} ({Key}) is present in {File}, which is not git-ignored. Move it to " +
            "appsettings.Local.json or an environment variable, then rotate the exposed value.",
            label, key, file);
}

// Silence here would be the worst outcome: notifications that were never going to arrive look
// exactly like notifications nobody happened to send.
if (!string.IsNullOrWhiteSpace(pushOptions.PublicKey) && !VapidKeys.IsValidPublicKey(pushOptions.PublicKey))
{
    app.Logger.LogWarning(
        "Push:PublicKey is not a valid VAPID public key (it must be a 65-byte uncompressed P-256 " +
        "point, base64url). Browsers will refuse to subscribe. Generate a pair with: dotnet run " +
        "--project backend/AiReceptionist.Api -- vapid");
}
// Apple is the strict one here, and it fails in the least obvious way: Android and desktop keep
// working, so the deployment looks healthy while every iPhone silently receives nothing.
else if (pushOptions.Configured && !pushOptions.SubjectUsable)
{
    app.Logger.LogWarning(
        "Push:Subject is {Subject}, which Apple's push service will reject — iPhones and iPads " +
        "will register successfully and then never receive a notification, while Android and " +
        "desktop keep working. Set it to a routable address you own, e.g. mailto:you@yourdomain.com " +
        "or https://yourdomain.com, in appsettings.Local.json or PUSH__SUBJECT.",
        pushOptions.Subject);
}
else if (!pushOptions.Configured)
{
    app.Logger.LogInformation(
        "Browser notifications are off — no VAPID key pair in Push:PublicKey / Push:PrivateKey. " +
        "Alerts still queue on the dashboard. Generate a pair with: dotnet run --project " +
        "backend/AiReceptionist.Api -- vapid");
}

// The "_"-prefixed entries in appsettings.json are documentation — nothing reads them — so a real
// secret parked there is exposed for no functional benefit. Prose has spaces; secrets do not.
foreach (var slot in new[] { "Retell:_ApiKey", "Jwt:_Secret", "Platform:_AdminKey" })
{
    if (app.Configuration[slot] is { Length: > 0 } note && !note.Contains(' '))
        app.Logger.LogWarning(
            "SECURITY: {Slot} in appsettings.json holds a value that looks like a real secret. That " +
            "entry is a comment and is never read — delete it and rotate the value.", slot);
}

// A key resolved from configuration rather than the RetellConnection row still works, but it means
// the super admin console is not the source of truth and rotation needs a redeploy.
try
{
    using var scope = app.Services.CreateScope();
    var stored = await scope.ServiceProvider.GetRequiredService<IRetellConnectionRepository>().GetAsync();
    if (string.IsNullOrWhiteSpace(stored?.ApiKey) && !string.IsNullOrWhiteSpace(app.Configuration["Retell:ApiKey"]))
        app.Logger.LogWarning(
            "Retell API key is resolving from configuration, not the RetellConnection row. Set it in " +
            "the super admin console (Retell AI) so it can be rotated without a redeploy.");
}
catch (Exception ex)
{
    app.Logger.LogDebug(ex, "Skipped the Retell key source check (database unavailable).");
}

// ---------- Pipeline ----------
app.UseMiddleware<ExceptionMiddleware>();

// Swagger publishes a complete map of every endpoint and payload shape — useful to an attacker
// probing production, so keep it to non-production environments.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}
else
{
    app.UseHsts();
}

app.UseResponseCompression();
app.UseCors("Frontend");

// Payload encryption sits inside compression (so what goes on the wire is the compressed form
// of the sealed body, and Content-Encoding still describes it) and inside CORS (so the browser
// is allowed to read a session-expired response and retry the handshake). Everything after this
// point — rate limiter rejections, 401s, validation errors, controller output — is sealed for a
// client that presents a session; Retell and the platform endpoints are exempt by path.
if (app.Configuration.GetValue("Encryption:Enabled", true))
    app.UseMiddleware<PayloadEncryptionMiddleware>();

app.UseRateLimiter();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
app.MapHealthChecks("/health");

app.Run();

/// <summary>Tracked (non "*.Local.json") config files carrying a value for <paramref name="key"/>.
/// Every provider is inspected rather than just the winning one, because a committed secret that
/// happens to be shadowed by a local override is still a committed secret.</summary>
static IEnumerable<string> TrackedConfigFilesFor(IConfiguration config, string key)
{
    if (config is not IConfigurationRoot root) yield break;

    foreach (var provider in root.Providers)
    {
        if (!provider.TryGet(key, out var value) || string.IsNullOrWhiteSpace(value)) continue;

        if ((provider as FileConfigurationProvider)?.Source.Path is { } path &&
            !path.Contains(".Local.", StringComparison.OrdinalIgnoreCase))
            yield return path;
    }
}
